version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: test
          command: npm run test

workflows:
  sample:
    jobs:
      - test
